services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: ./my-cal
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped